# Site settings
title: Jiro's Profile
email: jiro@jirosworld.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to use GitHub pages with LGBT Patchwork!
baseurl: "/patchwork-gh-pages-24"
url: "http://jolarti.github.io"
twitter_username: JirosWorld
github_username:  jolarti
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
